-- Waitlist promotion, the SMS offer flow, and the outbox the gateway drains.
--
-- Until now the offer flow only existed as demo state in the React app: the
-- 'offered' status was in the schema but nothing ever set it. This moves the
-- whole flow server-side, where capacity and fairness can actually be
-- enforced, and queues the notifications for the Edge Function to send.

-- ============================================================
-- SMS OUTBOX
-- Rows are written by the functions below and drained by the
-- send-sms Edge Function (service role). Never written by clients.
-- ============================================================
create table public.sms_outbox (
  id uuid primary key default gen_random_uuid(),
  center_id uuid not null references public.centers (id),
  player_id uuid references public.profiles (id) on delete set null,
  event_id uuid references public.events (id) on delete set null,
  phone text not null,
  body text not null,
  kind text not null check (kind in ('waitlist_offer', 'event_cancelled')),
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  attempts integer not null default 0,
  provider_message_id text,
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index sms_outbox_pending_idx on public.sms_outbox (status, created_at)
  where status = 'pending';

alter table public.sms_outbox enable row level security;

-- Admins may look at their own center's log; nobody writes from a client.
create policy "admins read center sms log"
  on public.sms_outbox for select
  using (public.is_center_admin() and center_id = public.current_center_id());

-- ============================================================
-- OFFER BOOKKEEPING
-- ============================================================
alter table public.event_registrations add column offered_at timestamptz;
alter table public.event_registrations add column offer_expires_at timestamptz;

-- Strict arrival order for the waitlist. created_at is not enough: it
-- defaults to now(), which is the transaction timestamp, so two sign-ups
-- made in the same transaction — or in the same millisecond — would tie and
-- fall back to comparing random uuids. The queue decides who gets a freed
-- spot, so it has to be exact.
alter table public.event_registrations add column seq bigint generated by default as identity;
create index registrations_waitlist_order_idx
  on public.event_registrations (event_id, seq)
  where status = 'waitlist';

comment on column public.event_registrations.offer_expires_at is
  'When an offered spot falls back to the next player on the waitlist.';

-- How long a player has to accept before the spot moves on. Capped by the
-- event start: an offer never outlives the match day it is for.
create or replace function public.offer_window()
returns interval
language sql
immutable
as $$ select interval '6 hours' $$;

-- Danish, because it is read by a player on their phone.
create or replace function public.sms_offer_body(p_event_id uuid, p_player_id uuid)
returns text
language plpgsql
stable
set search_path = public
as $$
declare
  ev public.events%rowtype;
  first_name text;
  starts text;
  deadline text;
begin
  select * into ev from public.events where id = p_event_id;
  select split_part(full_name, ' ', 1) into first_name from public.profiles where id = p_player_id;

  starts := to_char(ev.starts_at at time zone 'Europe/Copenhagen', 'DD.MM. "kl." HH24:MI');
  deadline := to_char(
    least(now() + public.offer_window(), ev.starts_at) at time zone 'Europe/Copenhagen',
    'DD.MM. "kl." HH24:MI');

  return format(
    'Hej %s! Der er blevet en plads ledig til %s %s. Pladsen er reserveret til dig indtil %s – bekraeft i appen: https://lapista.dk/e/%s',
    first_name, ev.title, starts, deadline, ev.id);
end;
$$;

create or replace function public.queue_sms(
  p_center_id uuid,
  p_player_id uuid,
  p_event_id uuid,
  p_kind text,
  p_body text
)
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  target_phone text;
begin
  select nullif(trim(coalesce(phone, '')), '') into target_phone
  from public.profiles where id = p_player_id;

  -- No phone number, nothing to send. The in-app state is still correct,
  -- so this is not an error.
  if target_phone is null then
    return;
  end if;

  insert into public.sms_outbox (center_id, player_id, event_id, phone, body, kind)
  values (p_center_id, p_player_id, p_event_id, target_phone, p_body, p_kind);
end;
$$;

-- ============================================================
-- promote_waitlist: fill every free spot with the next player in line.
-- Called whenever a spot opens (cancellation, admin removal, capacity
-- raise) and by the expiry job. Offered spots count against capacity,
-- so a spot is never handed to two players at once.
-- ============================================================
create or replace function public.promote_waitlist(p_event_id uuid)
returns integer
language plpgsql security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
  taken integer;
  cand public.event_registrations%rowtype;
  promoted integer := 0;
  expires timestamptz;
begin
  select * into ev from public.events where id = p_event_id for update;
  if ev.id is null or ev.status <> 'open' or ev.starts_at <= now() then
    return 0;
  end if;

  expires := least(now() + public.offer_window(), ev.starts_at);

  loop
    select count(*) into taken
    from public.event_registrations
    where event_id = p_event_id and status in ('registered', 'offered');
    exit when taken >= ev.capacity;

    select * into cand
    from public.event_registrations
    where event_id = p_event_id and status = 'waitlist'
    order by seq
    limit 1
    for update skip locked;
    exit when not found;

    update public.event_registrations
    set status = 'offered', offered_at = now(), offer_expires_at = expires
    where id = cand.id;

    perform public.queue_sms(
      ev.center_id, cand.player_id, ev.id, 'waitlist_offer',
      public.sms_offer_body(ev.id, cand.player_id));

    promoted := promoted + 1;
  end loop;

  return promoted;
end;
$$;

-- ============================================================
-- accept_offer / decline_offer: the two ends of the SMS link.
-- ============================================================
create or replace function public.accept_offer(p_event_id uuid)
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  reg public.event_registrations%rowtype;
begin
  select * into reg from public.event_registrations
  where event_id = p_event_id and player_id = auth.uid() and status = 'offered'
  for update;

  if not found then
    raise exception 'NO_OFFER';
  end if;
  if reg.offer_expires_at is not null and reg.offer_expires_at <= now() then
    raise exception 'OFFER_EXPIRED';
  end if;

  update public.event_registrations
  set status = 'registered', offered_at = null, offer_expires_at = null
  where id = reg.id;
end;
$$;

create or replace function public.decline_offer(p_event_id uuid)
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  reg public.event_registrations%rowtype;
begin
  select * into reg from public.event_registrations
  where event_id = p_event_id and player_id = auth.uid() and status = 'offered'
  for update;

  if not found then
    raise exception 'NO_OFFER';
  end if;

  update public.event_registrations
  set status = 'cancelled', offered_at = null, offer_expires_at = null
  where id = reg.id;

  perform public.promote_waitlist(p_event_id);
end;
$$;

-- ============================================================
-- expire_offers: an unanswered offer must not park a spot forever.
-- Run on a schedule by the Edge Function (service role).
-- ============================================================
create or replace function public.expire_offers()
returns integer
language plpgsql security definer
set search_path = public
as $$
declare
  ev_id uuid;
  expired integer := 0;
begin
  for ev_id in
    select distinct event_id from public.event_registrations
    where status = 'offered' and offer_expires_at is not null and offer_expires_at <= now()
  loop
    update public.event_registrations
    set status = 'cancelled', offered_at = null, offer_expires_at = null
    where event_id = ev_id and status = 'offered' and offer_expires_at <= now();

    expired := expired + 1;
    perform public.promote_waitlist(ev_id);
  end loop;

  return expired;
end;
$$;

-- ============================================================
-- leave_event: unchanged rules, but a freed spot now moves on to the
-- waitlist instead of silently shrinking the field.
-- ============================================================
create or replace function public.leave_event(p_event_id uuid)
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
  reg public.event_registrations%rowtype;
  freed_spot boolean;
begin
  select * into ev from public.events where id = p_event_id;
  if ev.id is null then
    raise exception 'EVENT_NOT_FOUND';
  end if;

  select * into reg from public.event_registrations
  where event_id = p_event_id and player_id = auth.uid()
    and status in ('registered', 'waitlist', 'offered');
  if reg.id is null then
    return;
  end if;

  -- DOMAIN RULE: a confirmed spot cannot self-cancel within 24h of start;
  -- the player has to contact the center so an admin can free the spot.
  if reg.status = 'registered' and ev.starts_at <= now() + interval '24 hours' then
    raise exception 'CANCEL_WINDOW_CLOSED';
  end if;

  freed_spot := reg.status in ('registered', 'offered');

  update public.event_registrations
  set status = 'cancelled', offered_at = null, offer_expires_at = null
  where id = reg.id;

  if freed_spot then
    perform public.promote_waitlist(p_event_id);
  end if;
end;
$$;

-- ============================================================
-- ADMIN ACTIONS that change who holds a spot.
-- Routed through RPCs so the waitlist and the SMS log stay correct —
-- a bare UPDATE from the client would skip both.
-- ============================================================
create or replace function public.admin_remove_registration(p_event_id uuid, p_player_id uuid)
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
begin
  if not public.is_center_admin() then
    raise exception 'NOT_ADMIN';
  end if;
  select * into ev from public.events where id = p_event_id;
  if ev.id is null or ev.center_id <> public.current_center_id() then
    raise exception 'EVENT_NOT_FOUND';
  end if;

  update public.event_registrations
  set status = 'cancelled', offered_at = null, offer_expires_at = null
  where event_id = p_event_id and player_id = p_player_id
    and status in ('registered', 'waitlist', 'offered');

  perform public.promote_waitlist(p_event_id);
end;
$$;

create or replace function public.admin_add_registration(p_event_id uuid, p_player_id uuid)
returns text
language plpgsql security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
  target public.profiles%rowtype;
  taken integer;
  new_status text;
begin
  if not public.is_center_admin() then
    raise exception 'NOT_ADMIN';
  end if;
  select * into ev from public.events where id = p_event_id;
  if ev.id is null or ev.center_id <> public.current_center_id() then
    raise exception 'EVENT_NOT_FOUND';
  end if;
  select * into target from public.profiles where id = p_player_id;
  if target.id is null or target.center_id <> ev.center_id then
    raise exception 'PLAYER_NOT_FOUND';
  end if;

  select count(*) into taken from public.event_registrations
  where event_id = p_event_id and status in ('registered', 'offered');

  new_status := case when taken < ev.capacity then 'registered' else 'waitlist' end;

  insert into public.event_registrations (center_id, event_id, player_id, status)
  values (ev.center_id, p_event_id, p_player_id, new_status)
  on conflict (event_id, player_id) do update
    set status = new_status, offered_at = null, offer_expires_at = null;

  return new_status;
end;
$$;

-- Raising the capacity opens spots, so the waitlist moves up with it.
create or replace function public.admin_set_capacity(p_event_id uuid, p_capacity integer)
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
begin
  if not public.is_center_admin() then
    raise exception 'NOT_ADMIN';
  end if;
  select * into ev from public.events where id = p_event_id;
  if ev.id is null or ev.center_id <> public.current_center_id() then
    raise exception 'EVENT_NOT_FOUND';
  end if;
  if p_capacity is null or p_capacity < 4 then
    raise exception 'INVALID_CAPACITY';
  end if;

  update public.events set capacity = p_capacity where id = p_event_id;
  perform public.promote_waitlist(p_event_id);
end;
$$;

-- Cancelling a day tells everyone who had a spot or was waiting.
create or replace function public.admin_cancel_event(p_event_id uuid)
returns integer
language plpgsql security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
  reg record;
  notified integer := 0;
  starts text;
begin
  if not public.is_center_admin() then
    raise exception 'NOT_ADMIN';
  end if;
  select * into ev from public.events where id = p_event_id;
  if ev.id is null or ev.center_id <> public.current_center_id() then
    raise exception 'EVENT_NOT_FOUND';
  end if;
  if ev.status = 'cancelled' then
    return 0;
  end if;

  starts := to_char(ev.starts_at at time zone 'Europe/Copenhagen', 'DD.MM. "kl." HH24:MI');

  for reg in
    select r.player_id, p.full_name
    from public.event_registrations r
    join public.profiles p on p.id = r.player_id
    where r.event_id = p_event_id and r.status in ('registered', 'waitlist', 'offered')
  loop
    perform public.queue_sms(
      ev.center_id, reg.player_id, ev.id, 'event_cancelled',
      format('Hej %s. %s %s er desvaerre aflyst. Vi ses naeste gang!',
        split_part(reg.full_name, ' ', 1), ev.title, starts));
    notified := notified + 1;
  end loop;

  update public.events set status = 'cancelled' where id = p_event_id;
  update public.event_registrations
  set status = 'cancelled', offered_at = null, offer_expires_at = null
  where event_id = p_event_id and status in ('registered', 'waitlist', 'offered');

  return notified;
end;
$$;

-- ============================================================
-- GRANTS: internal machinery stays internal.
-- ============================================================
revoke execute on function public.offer_window() from public, anon, authenticated;
revoke execute on function public.sms_offer_body(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.queue_sms(uuid, uuid, uuid, text, text) from public, anon, authenticated;
revoke execute on function public.promote_waitlist(uuid) from public, anon, authenticated;
revoke execute on function public.expire_offers() from public, anon, authenticated;
grant execute on function public.expire_offers() to service_role;

revoke execute on function public.accept_offer(uuid) from public, anon, authenticated;
grant execute on function public.accept_offer(uuid) to authenticated;
revoke execute on function public.decline_offer(uuid) from public, anon, authenticated;
grant execute on function public.decline_offer(uuid) to authenticated;
revoke execute on function public.leave_event(uuid) from public, anon, authenticated;
grant execute on function public.leave_event(uuid) to authenticated;
revoke execute on function public.admin_remove_registration(uuid, uuid) from public, anon, authenticated;
grant execute on function public.admin_remove_registration(uuid, uuid) to authenticated;
revoke execute on function public.admin_add_registration(uuid, uuid) from public, anon, authenticated;
grant execute on function public.admin_add_registration(uuid, uuid) to authenticated;
revoke execute on function public.admin_set_capacity(uuid, integer) from public, anon, authenticated;
grant execute on function public.admin_set_capacity(uuid, integer) to authenticated;
revoke execute on function public.admin_cancel_event(uuid) from public, anon, authenticated;
grant execute on function public.admin_cancel_event(uuid) to authenticated;
